### post weaning, predict which day from day 5 to day 7 have a esturs

In [1]:
# Batch 1 total 11, exluded 928 970, 154, 29, missing 44 31 43
pig_1  = ["981", #"29", "44", "31", "43"
             "151",  "919",
            "152","804",  "850", "974", "153"]

estrus_1 = {
    '981': ('2022-07-27', "6"),
    #'29': ('2022-07-29', "8"),
    '151':('2022-07-26', "5"),
    #'44': ('2022-07-27', "6"),
    '919': ('2022-07-26', "5"),
    #'43': ('2022-07-26', "5"),
    '152': ('2022-07-26', "5"),
    '804': ('2022-07-28', "7"),
    #'31': ('2022-07-26', "5"),
    '850': ('2022-07-28', "7"),
    '974': ('2022-07-27', "6"),
    '153': ('2022-07-27', "6"),
}

# Batch 2 total 9, exluded 931 927 775 850
pig_2  =  [ "138", "848", "777", "809", "984",
            "849", "139", "866", "506"]
estrus_2 = {
    '138': ('2022-09-01', "7"),
    '848': ('2022-08-31', "6"),
    '777': ('2022-08-31', "6"),
    '809': ('2022-08-30', "5"),
    '984': ('2022-08-31', "6"),
    '849': ('2022-08-31', "6"),
    '139': ('2022-09-01', "7"),
    '866': ('2022-08-30', "5"),
    '506': ('2022-08-30', "5"),
}

# Batch 3 total 19, exluded 16,204,214,97, missed "73","40","49", "15","14"
pig_3 = ["947", "842", "950", "814", "782", "158",
         "951", "790",  "157"]
estrus_3 = {
     '947': ('2022-10-06', "7"),
    '842': ('2022-10-04', "5"),
    '950': ('2022-10-06', "6"),
    '814': ('2022-10-04', "5"),
    '782': ('2022-10-04', "5"),
    '158': ('2022-10-05', "6"),
    '73': ('2022-10-04', "5"),
    '40': ('2022-10-04', "5"),
    '49': ('2022-10-06', "6"),
    '951': ('2022-10-04', "5"),
    '790': ('2022-10-04', "5"),
    '15': ('2022-10-04', "5"),
    '14': ('2022-10-04', "5"),
    '157': ('2022-10-04', "5"),
}

# Batch 4 total 12, exluded 40987, 40114, 40076, 40032, 44107, 44212, 44219
pig_4 = [
    "40054", "40086", "40051", "40040",
    "40319", "40115", #"40987",
    "40141","40883", "40026", "40867", "40060", "40069"
]

estrus_4 = {
    '40054': ('2022-11-09', "6"),
    '40086': ('2022-11-10', "7"),
    '40051': ('2022-11-08', "5"),
    '40040': ('2022-11-09', "6"),
    '40319': ('2022-11-08', "5"),
    '40115': ('2022-11-09', "6"),
    #'40987': ('2022-11-11', "no"),
    '40141': ('2022-11-08', "5"),
    '40883': ('2022-11-09', "6"),
    '40026': ('2022-11-08', "5"),
    '40867': ('2022-11-08', "5"),
    '40060': ('2022-11-08', "5"),
    '40069': ('2022-11-08', "5"),
}


# Batch 5, total 14,
pig_5 = [
    "50805", "50089", "50221", "50151", "50974", "50919", "50094",
    "50222", "50981", "50043", "50078", "50079", "50031", "50152"
]
estrus_5 = {
 '50805': ('2022-12-15', "7"),
    '50089': ('2022-12-14', "6"),
    '50221': ('2022-12-13', "5"),
    '50151': ('2022-12-14', "6"),
    '50974': ('2022-12-13', "5"),
    '50919': ('2022-12-13', "5"),
    '50094': ('2022-12-14', "6"),
    '50222': ('2022-12-14', "6"),
    '50981': ('2022-12-14', "6"),
    '50043': ('2022-12-13', "5"),
    '50078': ('2022-12-15', "7"),
    '50079': ('2022-12-13', "6"),
    '50031': ('2022-12-14', "6"),
    '50152': ('2022-12-14', "6"),
}


# Batch 6, total 11,  estrus data missing 60050, 60216,60091,60098 60506 60927 60777
pig_6 = [
    "60809", "60206", "60048", "60984", "60092",
    "60038", "60039", "60155", "60093", "60866", "60049"
]

estrus_6= {
    '60809': ('2023-01-17', "5"),
    '60206': ('2023-01-17', "5"),
    '60048': ('2023-01-18', "6"),
    '60984': ('2023-01-17', "5"),
    '60092': ('2023-01-17', "5"),
    '60038': ('2023-01-18', "6"),
    '60039': ('2023-01-18', "6"),
    '60155': ('2023-01-17', "5"),
    '60093': ('2023-01-18', "6"),
    '60866': ('2023-01-17', "5"),
    '60049': ('2023-01-19', "7")
    }

# Batch 7, total 8, esturs data missing 70204, 70096, 70049, 70951, 70111

pig_7 = [
    "70157", "70947", "70040", "70950",
    "70014", "70814",  "70790", "70951"
]

estrus_7 = {
    '70157': ('2023-02-22', "6"),
    '70947': ('2023-02-23', "7"),
    '70040': ('2023-02-22', "6"),
    '70950': ('2023-02-22', "6"),
    '70014': ('2023-02-21', "5"),
    '70814': ('2023-02-21', "5"),
    '70790': ('2023-02-21', "5"),
    '70951': ('2023-02-21', "5")
}


all_pigs = pig_1 + pig_2 + pig_3 + pig_4 + pig_5 + pig_6 + pig_7
estrus_dates = { **estrus_1, **estrus_2, **estrus_3, **estrus_4, **estrus_5, **estrus_6, **estrus_7}

In [2]:
def split_pigs(all_pigs, estrus_dates, train_ratio=0.6, val_ratio=0.2, test_ratio=0.2, seed=42):
    """
    Split pigs into training, validation, and test sets while maintaining class distribution
    """
    import numpy as np
    np.random.seed(seed)

    # Group pigs by their estrus day
    day_groups = {}
    for pig in all_pigs:
        day = estrus_dates[pig][1]
        if day not in day_groups:
            day_groups[day] = []
        day_groups[day].append(pig)

    train_pigs = []
    val_pigs = []
    test_pigs = []

    # Print initial group sizes
    print("\nInitial group sizes:")
    for day, pigs in day_groups.items():
        print(f"Day {day}: {len(pigs)} pigs")

    for day, pigs in day_groups.items():
        np.random.shuffle(pigs)
        n_pigs = len(pigs)

        # Calculate exact numbers, ensuring they sum to n_pigs
        n_train = round(n_pigs * train_ratio)
        n_val = round(n_pigs * val_ratio)
        n_test = n_pigs - n_train - n_val  # Ensure total adds up to n_pigs

        print(f"\nSplitting Day {day} ({n_pigs} pigs):")
        print(f"Training: {n_train} pigs ({n_train/n_pigs*100:.1f}%)")
        print(f"Validation: {n_val} pigs ({n_val/n_pigs*100:.1f}%)")
        print(f"Testing: {n_test} pigs ({n_test/n_pigs*100:.1f}%)")

        train_pigs.extend(pigs[:n_train])
        val_pigs.extend(pigs[n_train:n_train + n_val])
        test_pigs.extend(pigs[n_train + n_val:])

    total_pigs = len(train_pigs) + len(val_pigs) + len(test_pigs)
    print(f"\nFinal distribution:")
    print(f"Training: {len(train_pigs)}/{total_pigs} ({len(train_pigs)/total_pigs*100:.1f}%)")
    print(f"Validation: {len(val_pigs)}/{total_pigs} ({len(val_pigs)/total_pigs*100:.1f}%)")
    print(f"Testing: {len(test_pigs)}/{total_pigs} ({len(test_pigs)/total_pigs*100:.1f}%)")

    return train_pigs, val_pigs, test_pigs

In [ ]:
def set_seed(seed=42):
    """
    Set seeds for reproducibility
    """
    import random
    import numpy as np
    import torch

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, SubsetRandomSampler
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, confusion_matrix, f1_score
from datetime import datetime
import itertools
import json
import matplotlib.pyplot as plt
import seaborn as sns

class ImprovedPigTransformer(nn.Module):
    def __init__(self, input_dim=5, num_heads=4, num_layers=4, d_model=128, dropout=0.2):
        super().__init__()
        self.input_norm = nn.LayerNorm(input_dim)
        self.input_projection = nn.Sequential(
            nn.Linear(input_dim, d_model),
            nn.GELU(),
            nn.Dropout(dropout)
        )
        self.pos_encoding = nn.Parameter(torch.randn(1, 144, d_model) * 0.02)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=num_heads,
            dim_feedforward=d_model*4,
            dropout=dropout,
            activation='gelu',
            batch_first=True,
            norm_first=True
        )
        self.transformer_encoder = nn.TransformerEncoder(
            encoder_layer,
            num_layers=num_layers
        )

        self.attention_norm = nn.LayerNorm(d_model)
        self.global_attention = nn.MultiheadAttention(
            d_model,
            1,
            dropout=dropout,
            batch_first=True
        )

        self.classifier = nn.Sequential(
            nn.LayerNorm(d_model),
            nn.Linear(d_model, d_model // 2),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(d_model // 2, d_model // 4),
            nn.GELU(),
            nn.Dropout(dropout/2),
            nn.Linear(d_model // 4, 4)
        )

    def forward(self, x, mask=None):
        x = x.float()
        x = self.input_norm(x)
        x = self.input_projection(x)
        x = x + self.pos_encoding[:, :x.size(1), :]
        x = self.transformer_encoder(x, src_key_padding_mask=mask)

        x = self.attention_norm(x)
        query = torch.mean(x, dim=1, keepdim=True)
        pooled, _ = self.global_attention(query, x, x)
        pooled = pooled.squeeze(1)

        logits = self.classifier(pooled)
        return logits

class ImprovedPigDataset(Dataset):
    def __init__(self, pig_ids, sorted_files_dir, estrus_dates, mode='train', seq_length=144):
        super().__init__()
        self.pig_ids = pig_ids
        self.sorted_files_dir = sorted_files_dir
        self.estrus_dates = estrus_dates
        self.seq_length = seq_length
        self.mode = mode
        self.data = self._load_all_data()
        self.sequences = self._prepare_sequences()

    def _get_label(self, pig_id):
        if pig_id not in self.estrus_dates:
            return 0
        _, day = self.estrus_dates[pig_id]
        if day is None or day == "no":
            return 0
        return int(day) - 4

    def _load_all_data(self):
        all_data = {}
        scaler = MinMaxScaler()

        for pig_id in self.pig_ids:
            try:
                df = pd.read_csv(f"{self.sorted_files_dir}/{pig_id}_segments_sorted.txt")

                df['timestamp'] = pd.to_datetime(df['filename'].apply(
                    lambda x: '_'.join(x.split('_')[1:7])),
                    format='%Y_%m_%d_%H_%M_%S')

                estrus_date = pd.to_datetime(self.estrus_dates[pig_id][0]) if pig_id in self.estrus_dates else None

                if estrus_date is not None:
                    # Use 4 days before estrus date
                    start_date = estrus_date - pd.Timedelta(days=4)
                    end_date = estrus_date - pd.Timedelta(days=1)

                    mask = df['timestamp'].between(start_date, end_date + pd.Timedelta(days=1) - pd.Timedelta(seconds=1))
                    df = df[mask].copy()

                    if len(df) == 0:
                        print(f"No data for pig {pig_id} in {self.mode} mode")
                        continue

                    df['day_label'] = self._get_label(pig_id)

                    # Feature processing
                    df['normalized_area'] = scaler.fit_transform(
                        df['segment_1_area_size'].values.reshape(-1, 1))

                    df['hour'] = df['timestamp'].dt.hour
                    df['minute'] = df['timestamp'].dt.minute
                    df['time_of_day'] = df['hour'] + df['minute']/60

                    df['hour_sin'] = np.sin(2 * np.pi * df['time_of_day'] / 24)
                    df['hour_cos'] = np.cos(2 * np.pi * df['time_of_day'] / 24)

                    df['area_change'] = df['normalized_area'].diff().fillna(0)
                    df['activity_level'] = df['area_change'].abs()

                    all_data[pig_id] = df

            except Exception as e:
                print(f"Error processing pig {pig_id}: {str(e)}")
                continue

        return all_data

    def _prepare_sequences(self):
        sequences = []

        for pig_id, df in self.data.items():
            df = df.sort_values('timestamp')

            for i in range(len(df) - self.seq_length + 1):
                seq_df = df.iloc[i:i+self.seq_length]

                seq_features = np.column_stack([
                    seq_df['normalized_area'].values,
                    seq_df['area_change'].values,
                    seq_df['activity_level'].values,
                    seq_df['hour_sin'].values,
                    seq_df['hour_cos'].values
                ])

                seq_day_label = seq_df['day_label'].iloc[0]

                sequences.append({
                    'pig_id': pig_id,
                    'features': seq_features,
                    'day_label': seq_day_label,
                    'start_time': seq_df['timestamp'].iloc[0]
                })

        return sequences

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        seq = self.sequences[idx]
        return {
            'pig_id': seq['pig_id'],
            'features': torch.FloatTensor(seq['features']),
            'day_label': torch.LongTensor([seq['day_label']])[0],
            'start_time': seq['start_time'].strftime('%Y_%m_%d_%H_%M_%S')
        }


In [ ]:

def train_validate_test(train_pigs, val_pigs, test_pigs, estrus_dates, base_dir=".", seed=42):

    # Set seed for reproducibility
    set_seed(seed)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Create datasets
    train_dataset = ImprovedPigDataset(
        pig_ids=train_pigs,
        sorted_files_dir=base_dir,
        estrus_dates=estrus_dates,
        mode='train'
    )

    val_dataset = ImprovedPigDataset(
        pig_ids=val_pigs,
        sorted_files_dir=base_dir,
        estrus_dates=estrus_dates,
        mode='val'
    )

    test_dataset = ImprovedPigDataset(
        pig_ids=test_pigs,
        sorted_files_dir=base_dir,
        estrus_dates=estrus_dates,
        mode='test'
    )

    # Create data loaders with worker seed
    train_loader = DataLoader(
        train_dataset,
        batch_size=8,
        shuffle=True,
        num_workers=4,
        pin_memory=True,
        worker_init_fn=lambda worker_id: np.random.seed(seed + worker_id)
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=8,
        shuffle=False,
        num_workers=4,
        pin_memory=True,
        worker_init_fn=lambda worker_id: np.random.seed(seed + worker_id)
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=8,
        shuffle=False,
        num_workers=4,
        pin_memory=True,
        worker_init_fn=lambda worker_id: np.random.seed(seed + worker_id)
    )

    # Initialize model
    model = ImprovedPigTransformer(
        input_dim=5,
        num_heads=2,
        num_layers=2,
        d_model=128,
        dropout=0.1
    ).to(device)

    # Calculate class weights for balanced training
    labels = [data['day_label'] for data in train_dataset]
    class_counts = np.bincount(labels)
    class_weights = torch.FloatTensor(1.0 / np.maximum(class_counts, 1)).to(device)
    class_weights = class_weights / class_weights.sum()

    # Training setup
    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = torch.optim.AdamW(model.parameters(), lr=0.0001)
    num_epochs = 50
    best_val_f1 = 0
    patience = 10
    no_improve = 0

    # Print initial setup
    print(f"\nTraining with seed: {seed}")
    print(f"Device: {device}")
    print(f"Training samples: {len(train_dataset)}")
    print(f"Validation samples: {len(val_dataset)}")
    print(f"Test samples: {len(test_dataset)}")
    print(f"Class weights: {class_weights.cpu().numpy()}")

    # Training loop
    print("\nStarting training...")
    for epoch in range(num_epochs):
        # Training phase
        model.train()
        train_loss = 0
        train_preds = []
        train_labels = []

        for batch in train_loader:
            features = batch['features'].float().to(device)
            labels = batch['day_label'].to(device)

            optimizer.zero_grad()
            outputs = model(features)
            loss = criterion(outputs, labels)

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            train_loss += loss.item()
            train_preds.extend(outputs.argmax(1).cpu().numpy())
            train_labels.extend(labels.cpu().numpy())

        # Validation phase
        model.eval()
        val_loss = 0
        val_preds = []
        val_labels = []

        with torch.no_grad():
            for batch in val_loader:
                features = batch['features'].float().to(device)
                labels = batch['day_label'].to(device)

                outputs = model(features)
                loss = criterion(outputs, labels)

                val_loss += loss.item()
                val_preds.extend(outputs.argmax(1).cpu().numpy())
                val_labels.extend(labels.cpu().numpy())

        # Calculate metrics
        train_f1 = f1_score(train_labels, train_preds, average='weighted')
        val_f1 = f1_score(val_labels, val_preds, average='weighted')

        print(f"\nEpoch {epoch+1}/{num_epochs}")
        print(f"Train Loss: {train_loss/len(train_loader):.4f}, F1: {train_f1:.4f}")
        print(f"Val Loss: {val_loss/len(val_loader):.4f}, F1: {val_f1:.4f}")

        # Save best model
        if val_f1 > best_val_f1:
            best_val_f1 = val_f1
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'train_f1': train_f1,
                'val_f1': val_f1,
                'seed': seed,
                'class_weights': class_weights
            }, 'best_model.pth')
            no_improve = 0
        else:
            no_improve += 1
            if no_improve >= patience:
                print("Early stopping triggered")
                break

    # Load best model for testing
    checkpoint = torch.load('best_model.pth')
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()

    # Test phase
    test_preds = []
    test_labels = []

    with torch.no_grad():
        for batch in test_loader:
            features = batch['features'].float().to(device)
            labels = batch['day_label'].to(device)

            outputs = model(features)
            test_preds.extend(outputs.argmax(1).cpu().numpy())
            test_labels.extend(labels.cpu().numpy())

    # Calculate and print final metrics
    print("\nFinal Results:")

    print("\nTRAINING SET:")
    train_metrics = classification_report(train_labels, train_preds)
    print(train_metrics)
    print("Confusion Matrix:")
    print(confusion_matrix(train_labels, train_preds))

    print("\nVALIDATION SET:")
    val_metrics = classification_report(val_labels, val_preds)
    print(val_metrics)
    print("Confusion Matrix:")
    print(confusion_matrix(val_labels, val_preds))

    print("\nTEST SET:")
    test_metrics = classification_report(test_labels, test_preds)
    print(test_metrics)
    print("Confusion Matrix:")
    print(confusion_matrix(test_labels, test_preds))

    return model, {
        'train_metrics': classification_report(train_labels, train_preds, output_dict=True),
        'val_metrics': classification_report(val_labels, val_preds, output_dict=True),
        'test_metrics': classification_report(test_labels, test_preds, output_dict=True),
        'train_conf': confusion_matrix(train_labels, train_preds),
        'val_conf': confusion_matrix(val_labels, val_preds),
        'test_conf': confusion_matrix(test_labels, test_preds),
        'seed': seed,
        'best_epoch': checkpoint['epoch'],
        'final_train_f1': train_f1,
        'final_val_f1': val_f1,
        'best_val_f1': checkpoint['val_f1']
    }

# Usage
if __name__ == "__main__":
    # Set global seed
    SEED = 42
    set_seed(SEED)

    # Get train/val/test splits
    train_pigs, val_pigs, test_pigs = split_pigs(all_pigs, estrus_dates, seed=SEED)

    print(f"Running with seed: {SEED}")
    model, results = train_validate_test(
        train_pigs=train_pigs,
        val_pigs=val_pigs,
        test_pigs=test_pigs,
        estrus_dates=estrus_dates,
        seed=SEED
    )

    # Save complete results
    torch.save({
        'results': results,
        'seed': SEED,
        'train_pigs': train_pigs,
        'val_pigs': val_pigs,
        'test_pigs': test_pigs
    }, f'complete_results_seed_{SEED}.pth')


Initial group sizes:
Day 6: 28 pigs
Day 5: 33 pigs
Day 7: 10 pigs

Splitting Day 6 (28 pigs):
Training: 17 pigs (60.7%)
Validation: 6 pigs (21.4%)
Testing: 5 pigs (17.9%)

Splitting Day 5 (33 pigs):
Training: 20 pigs (60.6%)
Validation: 7 pigs (21.2%)
Testing: 6 pigs (18.2%)

Splitting Day 7 (10 pigs):
Training: 6 pigs (60.0%)
Validation: 2 pigs (20.0%)
Testing: 2 pigs (20.0%)

Final distribution:
Training: 43/71 (60.6%)
Validation: 15/71 (21.1%)
Testing: 13/71 (18.3%)
Running with seed: 42


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(



Training with seed: 42
Device: cuda
Training samples: 14353
Validation samples: 4885
Test samples: 4362
Class weights: [9.9922550e-01 1.6762715e-04 1.6266083e-04 4.4429768e-04]

Starting training...

Epoch 1/50
Train Loss: 1.0241, F1: 0.4832
Val Loss: 1.1276, F1: 0.3939

Epoch 2/50
Train Loss: 0.6903, F1: 0.7123
Val Loss: 1.3554, F1: 0.5224

Epoch 3/50
Train Loss: 0.4440, F1: 0.8283
Val Loss: 1.9585, F1: 0.4642

Epoch 4/50
Train Loss: 0.3146, F1: 0.9033
Val Loss: 2.4474, F1: 0.5238

Epoch 5/50
Train Loss: 0.2324, F1: 0.9423
Val Loss: 2.6223, F1: 0.5338

Epoch 6/50
Train Loss: 0.1881, F1: 0.9581
Val Loss: 3.2124, F1: 0.4945

Epoch 7/50
Train Loss: 0.1482, F1: 0.9690
Val Loss: 3.2855, F1: 0.5066

Epoch 8/50
Train Loss: 0.1347, F1: 0.9712
Val Loss: 4.2506, F1: 0.4596

Epoch 9/50
Train Loss: 0.1313, F1: 0.9740
Val Loss: 4.1798, F1: 0.4423

Epoch 10/50
Train Loss: 0.1048, F1: 0.9800
Val Loss: 3.5501, F1: 0.4571

Epoch 11/50
Train Loss: 0.1060, F1: 0.9788
Val Loss: 3.9286, F1: 0.4418

Epoch

<ipython-input-13-b21d1b1d97ff>:162: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load('best_model.pth')



Final Results:

TRAINING SET:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00      5961
           2       1.00      1.00      1.00      6143
           3       1.00      0.99      0.99      2249

    accuracy                           1.00     14353
   macro avg       1.00      1.00      1.00     14353
weighted avg       1.00      1.00      1.00     14353

Confusion Matrix:
[[5938   17    6]
 [  14 6125    4]
 [   5    9 2235]]

VALIDATION SET:
              precision    recall  f1-score   support

           1       0.60      0.53      0.56      1990
           2       0.53      0.73      0.62      2174
           3       0.03      0.01      0.01       721

    accuracy                           0.54      4885
   macro avg       0.39      0.42      0.39      4885
weighted avg       0.48      0.54      0.50      4885

Confusion Matrix:
[[1045  916   29]
 [ 471 1592  111]
 [ 222  495    4]]

TEST SET:
              precision    recall

#### 622

In [5]:
import os
import random
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from sklearn.metrics import classification_report, confusion_matrix, f1_score
import itertools

def set_seed(seed=42):
    """
    Set seeds for reproducibility with enhanced deterministic behavior
    """
    os.environ['PYTHONHASHSEED'] = str(seed)
    if torch.cuda.is_available():
        os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
        torch.use_deterministic_algorithms(True)

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

def create_deterministic_loader(dataset, batch_size, shuffle, num_workers, seed):
    """
    Create a deterministic DataLoader
    """
    generator = torch.Generator()
    generator.manual_seed(seed)

    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=num_workers,
        pin_memory=True,
        worker_init_fn=lambda worker_id: np.random.seed(seed + worker_id),
        generator=generator,
        persistent_workers=True,
        drop_last=False
    )

def optimize_and_train(train_pigs, val_pigs, test_pigs, estrus_dates, base_dir=".", seed=42):
    """
    Complete pipeline with optimization, training, validation, and testing
    """
    # Set seeds for reproducibility
    set_seed(seed)
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    print(f"Using device: {device}")
    if torch.cuda.is_available():
        print(f"GPU: {torch.cuda.get_device_name(0)}")
        print(f"CUDA Version: {torch.version.cuda}")
    print(f"PyTorch Version: {torch.__version__}")

    # Create datasets
    train_dataset = ImprovedPigDataset(
        pig_ids=train_pigs,
        sorted_files_dir=base_dir,
        estrus_dates=estrus_dates,
        mode='train'
    )

    val_dataset = ImprovedPigDataset(
        pig_ids=val_pigs,
        sorted_files_dir=base_dir,
        estrus_dates=estrus_dates,
        mode='val'
    )

    test_dataset = ImprovedPigDataset(
        pig_ids=test_pigs,
        sorted_files_dir=base_dir,
        estrus_dates=estrus_dates,
        mode='test'
    )

    # Define hyperparameter search space
    param_grid = {
        'num_heads': [4,8],
        'num_layers': [4, 6],
        'd_model': [128, 256],
        'dropout': [0.1],
        'learning_rate': [1e-4, 3e-4, 1e-3],
        'batch_size': [16, 32]
    }

    # Optimization phase
    print("Starting hyperparameter optimization...")
    best_params = optimize_hyperparameters(
        train_dataset, val_dataset, param_grid, device, seed=seed
    )
    print("\nBest hyperparameters found:")
    for param, value in best_params.items():
        print(f"{param}: {value}")

    # Create final data loaders with best batch size
    train_loader = create_deterministic_loader(
        train_dataset,
        batch_size=best_params['batch_size'],
        shuffle=True,
        num_workers=4,
        seed=seed
    )

    val_loader = create_deterministic_loader(
        val_dataset,
        batch_size=best_params['batch_size'],
        shuffle=False,
        num_workers=4,
        seed=seed
    )

    test_loader = create_deterministic_loader(
        test_dataset,
        batch_size=best_params['batch_size'],
        shuffle=False,
        num_workers=4,
        seed=seed
    )

    # Train final model with best parameters
    final_model, results = train_with_params(
        train_loader, val_loader, test_loader, best_params, device, seed=seed
    )

    return final_model, results, best_params

def optimize_hyperparameters(train_data, val_data, param_grid, device, seed=42):
    """
    Perform hyperparameter optimization using cross-validation
    """
    set_seed(seed)
    best_score = -1
    best_params = None

    # Get class weights for balanced training
    labels = [data['day_label'] for data in train_data]
    class_counts = np.bincount(labels)
    class_weights = torch.FloatTensor(1.0 / np.maximum(class_counts, 1)).to(device)
    class_weights = class_weights / class_weights.sum()

    # Generate parameter combinations
    param_combinations = [dict(zip(param_grid.keys(), v))
                        for v in itertools.product(*param_grid.values())]

    for params in param_combinations:
        print(f"\nTesting parameters: {params}")
        set_seed(seed)  # Reset seed for each parameter combination

        # Create data loaders
        train_loader = create_deterministic_loader(
            train_data,
            batch_size=params['batch_size'],
            shuffle=True,
            num_workers=4,
            seed=seed
        )

        val_loader = create_deterministic_loader(
            val_data,
            batch_size=params['batch_size'],
            shuffle=False,
            num_workers=4,
            seed=seed
        )

        # Initialize model
        model = ImprovedPigTransformer(
            input_dim=5,
            num_heads=params['num_heads'],
            num_layers=params['num_layers'],
            d_model=params['d_model'],
            dropout=params['dropout']
        ).to(device)

        # Training setup
        criterion = nn.CrossEntropyLoss(weight=class_weights)
        optimizer = torch.optim.AdamW(model.parameters(), lr=params['learning_rate'])

        # Quick training to evaluate parameters
        val_f1 = train_evaluation_run(
            model, train_loader, val_loader, criterion, optimizer, device, seed=seed
        )

        print(f"Validation F1: {val_f1:.4f}")

        if val_f1 > best_score:
            best_score = val_f1
            best_params = params.copy()  # Make a copy to ensure independence
            print("New best parameters found!")

    return best_params


def train_evaluation_run(model, train_loader, val_loader, criterion, optimizer, device,
                        max_epochs=10, seed=42):
    """
    Quick training run to evaluate parameters
    """
    set_seed(seed)
    best_val_f1 = 0

    for epoch in range(max_epochs):
        # Training
        model.train()
        for batch in train_loader:
            features = batch['features'].float().to(device)
            labels = batch['day_label'].to(device)

            optimizer.zero_grad()
            outputs = model(features)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

        # Validation
        model.eval()
        val_preds = []
        val_labels = []

        with torch.no_grad():
            for batch in val_loader:
                features = batch['features'].float().to(device)
                labels = batch['day_label'].to(device)

                outputs = model(features)
                val_preds.extend(outputs.argmax(1).cpu().numpy())
                val_labels.extend(labels.cpu().numpy())

        val_f1 = f1_score(val_labels, val_preds, average='weighted')
        best_val_f1 = max(best_val_f1, val_f1)

    return best_val_f1


def train_with_params(train_loader, val_loader, test_loader, params, device, seed=42):
    """
    Train final model with best parameters
    """
    set_seed(seed)

    # Initialize model with best parameters
    model = ImprovedPigTransformer(
        input_dim=5,
        num_heads=params['num_heads'],
        num_layers=params['num_layers'],
        d_model=params['d_model'],
        dropout=params['dropout']
    ).to(device)

    # Get class weights
    labels = []
    for batch in train_loader:
        labels.extend(batch['day_label'].numpy())
    class_counts = np.bincount(labels)
    class_weights = torch.FloatTensor(1.0 / np.maximum(class_counts, 1)).to(device)
    class_weights = class_weights / class_weights.sum()

    # Training setup
    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = torch.optim.AdamW(model.parameters(), lr=params['learning_rate'])
    scheduler = torch.optim.lr_scheduler.OneCycleLR(
        optimizer,
        max_lr=params['learning_rate'],
        epochs=50,
        steps_per_epoch=len(train_loader)
    )

    # Training loop
    best_val_f1 = 0
    patience = 10
    no_improve = 0

    print("\nTraining final model...")
    for epoch in range(50):
        # Training phase
        model.train()
        train_preds = []
        train_labels = []

        for batch in train_loader:
            features = batch['features'].float().to(device)
            labels = batch['day_label'].to(device)

            optimizer.zero_grad()
            outputs = model(features)
            loss = criterion(outputs, labels)

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()

            train_preds.extend(outputs.argmax(1).cpu().numpy())
            train_labels.extend(labels.cpu().numpy())

        # Validation phase
        model.eval()
        val_preds = []
        val_labels = []

        with torch.no_grad():
            for batch in val_loader:
                features = batch['features'].float().to(device)
                labels = batch['day_label'].to(device)

                outputs = model(features)
                val_preds.extend(outputs.argmax(1).cpu().numpy())
                val_labels.extend(labels.cpu().numpy())

        # Calculate metrics
        train_f1 = f1_score(train_labels, train_preds, average='weighted')
        val_f1 = f1_score(val_labels, val_preds, average='weighted')

        print(f"\nEpoch {epoch+1}/50")
        print(f"Train F1: {train_f1:.4f}")
        print(f"Val F1: {val_f1:.4f}")

        # Save best model
        if val_f1 > best_val_f1:
            best_val_f1 = val_f1
            torch.save({
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'scheduler_state_dict': scheduler.state_dict(),
                'epoch': epoch,
                'best_val_f1': best_val_f1,
                'seed': seed,
                'params': params
            }, 'best_model.pth')
            no_improve = 0
        else:
            no_improve += 1
            if no_improve >= patience:
                print("Early stopping triggered")
                break

    # Load best model for testing
    checkpoint = torch.load('best_model.pth')
    model.load_state_dict(checkpoint['model_state_dict'])

    # Final evaluation on all sets
    results = evaluate_model(model, train_loader, val_loader, test_loader, device)

    # Add training metadata to results
    results['training_metadata'] = {
        'seed': seed,
        'best_epoch': checkpoint['epoch'],
        'best_val_f1': checkpoint['best_val_f1'],
        'params': params
    }

    return model, results


def evaluate_model(model, train_loader, val_loader, test_loader, device):
    """
    Evaluate model on all datasets
    """
    model.eval()
    results = {}

    # Evaluate each dataset
    for name, loader in [('train', train_loader), ('val', val_loader), ('test', test_loader)]:
        predictions = []
        true_labels = []

        with torch.no_grad():
            for batch in loader:
                features = batch['features'].float().to(device)
                labels = batch['day_label'].to(device)

                outputs = model(features)
                predictions.extend(outputs.argmax(1).cpu().numpy())
                true_labels.extend(labels.cpu().numpy())

        # Calculate metrics
        metrics = classification_report(true_labels, predictions, output_dict=True)
        conf_matrix = confusion_matrix(true_labels, predictions)

        results[name] = {
            'metrics': metrics,
            'confusion_matrix': conf_matrix
        }

        # Print results
        print(f"\n{name.upper()} SET RESULTS:")
        print("\nClassification Report:")
        print(classification_report(true_labels, predictions))
        print("\nConfusion Matrix:")
        print(conf_matrix)

    return results


if __name__ == "__main__":
    # Set environment variables for deterministic behavior
    os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"

    # Set global seed
    SEED = 42
    set_seed(SEED)

    # Verify seed is working
    print("Verifying seed reproducibility:")
    print(f"Random number 1: {random.random()}")
    print(f"Numpy random 1: {np.random.rand(1)[0]}")
    print(f"Torch random 1: {torch.rand(1)[0].item()}")

    # Split pigs
    train_pigs, val_pigs, test_pigs = split_pigs(all_pigs, estrus_dates, seed=SEED)

    print(f"\nNumber of pigs in training set: {len(train_pigs)}")
    print(f"Number of pigs in validation set: {len(val_pigs)}")
    print(f"Number of pigs in test set: {len(test_pigs)}")

    print(f"\nRunning with seed: {SEED}")
    model, results, best_params = optimize_and_train(
        train_pigs=train_pigs,
        val_pigs=val_pigs,
        test_pigs=test_pigs,
        estrus_dates=estrus_dates,
        seed=SEED
    )

    # Save complete results with verification info
    torch.save({
        'results': results,
        'best_params': best_params,
        'seed': SEED,
        'train_pigs': train_pigs,
        'val_pigs': val_pigs,
        'test_pigs': test_pigs,
        'random_verification': {
            'random_num': random.random(),
            'numpy_random': np.random.rand(1)[0],
            'torch_random': torch.rand(1)[0].item()
        },
        'environment_info': {
            'pytorch_version': torch.__version__,
            'cuda_version': torch.version.cuda if torch.cuda.is_available() else None,
            'gpu_name': torch.cuda.get_device_name(0) if torch.cuda.is_available() else None,
        }
    }, f'complete_results_seed_{SEED}.pth')

Verifying seed reproducibility:
Random number 1: 0.6394267984578837
Numpy random 1: 0.3745401188473625
Torch random 1: 0.8822692632675171

Initial group sizes:
Day 6: 28 pigs
Day 5: 33 pigs
Day 7: 10 pigs

Splitting Day 6 (28 pigs):
Training: 17 pigs (60.7%)
Validation: 6 pigs (21.4%)
Testing: 5 pigs (17.9%)

Splitting Day 5 (33 pigs):
Training: 20 pigs (60.6%)
Validation: 7 pigs (21.2%)
Testing: 6 pigs (18.2%)

Splitting Day 7 (10 pigs):
Training: 6 pigs (60.0%)
Validation: 2 pigs (20.0%)
Testing: 2 pigs (20.0%)

Final distribution:
Training: 43/71 (60.6%)
Validation: 15/71 (21.1%)
Testing: 13/71 (18.3%)

Number of pigs in training set: 43
Number of pigs in validation set: 15
Number of pigs in test set: 13

Running with seed: 42
Using device: cuda
GPU: NVIDIA L4
CUDA Version: 12.1
PyTorch Version: 2.5.1+cu121
Starting hyperparameter optimization...

Testing parameters: {'num_heads': 4, 'num_layers': 4, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5222
New best parameters found!

Testing parameters: {'num_heads': 4, 'num_layers': 4, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5257
New best parameters found!

Testing parameters: {'num_heads': 4, 'num_layers': 4, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5440
New best parameters found!

Testing parameters: {'num_heads': 4, 'num_layers': 4, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.4679

Testing parameters: {'num_heads': 4, 'num_layers': 4, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.2741

Testing parameters: {'num_heads': 4, 'num_layers': 4, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.4756

Testing parameters: {'num_heads': 4, 'num_layers': 4, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5440
New best parameters found!

Testing parameters: {'num_heads': 4, 'num_layers': 4, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5560
New best parameters found!

Testing parameters: {'num_heads': 4, 'num_layers': 4, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.4776

Testing parameters: {'num_heads': 4, 'num_layers': 4, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.4878

Testing parameters: {'num_heads': 4, 'num_layers': 4, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.2741

Testing parameters: {'num_heads': 4, 'num_layers': 4, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.2741

Testing parameters: {'num_heads': 4, 'num_layers': 6, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5308

Testing parameters: {'num_heads': 4, 'num_layers': 6, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5668
New best parameters found!

Testing parameters: {'num_heads': 4, 'num_layers': 6, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5342

Testing parameters: {'num_heads': 4, 'num_layers': 6, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.4767

Testing parameters: {'num_heads': 4, 'num_layers': 6, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.2800

Testing parameters: {'num_heads': 4, 'num_layers': 6, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.3255

Testing parameters: {'num_heads': 4, 'num_layers': 6, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5611

Testing parameters: {'num_heads': 4, 'num_layers': 6, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.6334
New best parameters found!

Testing parameters: {'num_heads': 4, 'num_layers': 6, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.4574

Testing parameters: {'num_heads': 4, 'num_layers': 6, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.4377

Testing parameters: {'num_heads': 4, 'num_layers': 6, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.2741

Testing parameters: {'num_heads': 4, 'num_layers': 6, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.2741

Testing parameters: {'num_heads': 8, 'num_layers': 4, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5642

Testing parameters: {'num_heads': 8, 'num_layers': 4, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.6129

Testing parameters: {'num_heads': 8, 'num_layers': 4, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5107

Testing parameters: {'num_heads': 8, 'num_layers': 4, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.4612

Testing parameters: {'num_heads': 8, 'num_layers': 4, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.2741

Testing parameters: {'num_heads': 8, 'num_layers': 4, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.2741

Testing parameters: {'num_heads': 8, 'num_layers': 4, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5389

Testing parameters: {'num_heads': 8, 'num_layers': 4, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5140

Testing parameters: {'num_heads': 8, 'num_layers': 4, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.4462

Testing parameters: {'num_heads': 8, 'num_layers': 4, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5189

Testing parameters: {'num_heads': 8, 'num_layers': 4, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.2741

Testing parameters: {'num_heads': 8, 'num_layers': 4, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.2741

Testing parameters: {'num_heads': 8, 'num_layers': 6, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5697

Testing parameters: {'num_heads': 8, 'num_layers': 6, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5633

Testing parameters: {'num_heads': 8, 'num_layers': 6, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5375

Testing parameters: {'num_heads': 8, 'num_layers': 6, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5121

Testing parameters: {'num_heads': 8, 'num_layers': 6, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.2741

Testing parameters: {'num_heads': 8, 'num_layers': 6, 'd_model': 128, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.2741

Testing parameters: {'num_heads': 8, 'num_layers': 6, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5200

Testing parameters: {'num_heads': 8, 'num_layers': 6, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5339

Testing parameters: {'num_heads': 8, 'num_layers': 6, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.4464

Testing parameters: {'num_heads': 8, 'num_layers': 6, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.0003, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.5916

Testing parameters: {'num_heads': 8, 'num_layers': 6, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 16}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.2741

Testing parameters: {'num_heads': 8, 'num_layers': 6, 'd_model': 256, 'dropout': 0.1, 'learning_rate': 0.001, 'batch_size': 32}


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


Validation F1: 0.2741

Best hyperparameters found:
num_heads: 4
num_layers: 6
d_model: 256
dropout: 0.1
learning_rate: 0.0001
batch_size: 32


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(



Training final model...

Epoch 1/50
Train F1: 0.3847
Val F1: 0.2501

Epoch 2/50
Train F1: 0.4229
Val F1: 0.5073

Epoch 3/50
Train F1: 0.4605
Val F1: 0.5164

Epoch 4/50
Train F1: 0.5106
Val F1: 0.4265

Epoch 5/50
Train F1: 0.5694
Val F1: 0.4160

Epoch 6/50
Train F1: 0.6602
Val F1: 0.4597

Epoch 7/50
Train F1: 0.7633
Val F1: 0.4351

Epoch 8/50
Train F1: 0.8675
Val F1: 0.4741

Epoch 9/50
Train F1: 0.9214
Val F1: 0.4178

Epoch 10/50
Train F1: 0.9416
Val F1: 0.4848

Epoch 11/50
Train F1: 0.9592
Val F1: 0.4593

Epoch 12/50
Train F1: 0.9685
Val F1: 0.4566

Epoch 13/50
Train F1: 0.9733
Val F1: 0.4947
Early stopping triggered


<ipython-input-5-b571cbca0e7f>:345: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load('best_model.pth')



TRAIN SET RESULTS:

Classification Report:
              precision    recall  f1-score   support

           1       0.47      0.85      0.60      5961
           2       0.59      0.29      0.39      6143
           3       0.78      0.12      0.21      2249

    accuracy                           0.50     14353
   macro avg       0.61      0.42      0.40     14353
weighted avg       0.57      0.50      0.45     14353


Confusion Matrix:
[[5094  854   13]
 [4267 1810   66]
 [1586  385  278]]

VAL SET RESULTS:

Classification Report:
              precision    recall  f1-score   support

           1       0.48      0.79      0.60      1990
           2       0.72      0.53      0.61      2174
           3       0.00      0.00      0.00       721

    accuracy                           0.56      4885
   macro avg       0.40      0.44      0.40      4885
weighted avg       0.52      0.56      0.52      4885


Confusion Matrix:
[[1578  386   26]
 [1024 1150    0]
 [ 665   56    0]]

TES